fmod PEANO is
	sort PeanoNat .
	op 0 : -> PeanoNat [ctor] .
	op s : PeanoNat -> PeanoNat [ctor] .
	vars N M : PeanoNat .
	op _+_ : PeanoNat PeanoNat -> PeanoNat [assoc comm] .
	eq 0 + N = N .
	eq s(N) + M = s(N + M) .
	op _*_ : PeanoNat PeanoNat -> PeanoNat [assoc comm] .
	eq 0 * N = 0 .
	eq N * M = M + (N * M) .
	op pow : PeanoNat PeanoNat -> PeanoNat .
	eq pow(0,N) = 0 .
	eq pow(s(N),0) = s(0) .
	eq pow(s(N), s(M)) = s(N) * pow(s(N),M) .
endfm 
